version: 2.1

jobs:
  # lint_js:
  #   docker:
  #     - image: circleci/node:10
  #   steps:
  #     - checkout
  #     - run: npm ci
  #     - run: npm run lint
  tests:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm ci
      - run: npm run test
  # publish_to_npm:
  #   docker:
  #     - image: circleci/node:10
  #   steps:
  #     - checkout
  #     - run: npm ci
  #     - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
  #     - run: npm publish

workflows:
  test:
    jobs:
      # - lint_js:
      #     filters:
      #       tags:
      #         ignore: /^v.*/
      #       branches:
      #         ignore: master
      - tests:
          filters:
            tags:
              ignore: /^v.*/
            branches:
              ignore: master
      # - publish_to_npm:
      #     filters:
      #       tags:
      #         only: /^v.*/
      #       branches:
      #         ignore: /.*/
