version: 2

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm clean-install-test
  # publish_to_npm:
  #   docker:
  #     - image: circleci/node:10
  #   steps:
  #     - checkout
  #     - run: npm ci
  #     - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
  #     - run: npm publish

workflows:
  test:
    jobs:
      - build:
          filters:
            tags:
              ignore: /^v.*/
            branches:
              ignore: master
      # - publish_to_npm:
      #     filters:
      #       tags:
      #         only: /^v.*/
      #       branches:
      #         ignore: /.*/
