const nixt = require('nixt');

describe('Init', () => {
	it('Uses default values where possible to create folder tree', done => {
		nixt({ colors: false })
			.run('./bin/run')
			.on(/name/i).respond('bob\n')
			.on(/current directory/i).respond('\033[B\n')
			.on(/description/i).respond('bla bla\n')
			.on(/keywords/i).respond('\n')
			.on(/category/).respond('\n')
			.on(/brands/).respond('\n')
			.on(/JavaScript/).respond('\n')
			.on(/Sass/).respond('\n')
			.on(/status/).respond('\n')
			.on(/team email/).respond('\n')
			.on(/slack channel/).respond('\n')
			.on(/Github team/).respond('\n')
			.on(/right/).respond('\n')
			.exist('./bob/')
			.exist('./bob/src/js')
			.exist('./bob/src/scss')
			.exist('./bob/test/js')
			.exist('./bob/test/scss')
			.exist('./bob/demos')
			.exist('./bob/.github')
			.exec('rm -rf bob')
			.end(done)
	});

	it('Does not create Javascript files if not requested', (done) => {
		nixt({ colors: false })
			.run('./bin/run')
			.on(/name/i).respond('bob\n')
			.on(/directory/i).respond('\033[B\n')
			.on(/description/i).respond('bla bla\n')
			.on(/keywords/i).respond('\n')
			.on(/category/i).respond('\n')
			.on(/brands/).respond('\n')
			.on(/JavaScript/).respond('n\n')
			.on(/Sass/).respond('\n')
			.on(/status/).respond('\n')
			.on(/team email/).respond('\n')
			.on(/slack channel/).respond('\n')
			.on(/Github team/).respond('\n')
			.on(/right/).respond('\n')
			.exist('./bob/')
			.exist('./bob/src/scss')
			.exist('./bob/test/scss')
			.exist('./bob/demos')
			.exist('./bob/.github')
			.notExist('./bob/src/js')
			.notExist('./bob/test/js')
			.notExist('./bob/demo/demo.js')
			.exec('rm -rf bob')
			.end(done)
	});

	it('Does not create SCSS files if not requested', (done) => {
		nixt({ colors: false })
			.run('./bin/run')
			.on(/name/i).respond('bob\n')
			.on(/directory/i).respond('\033[B\n')
			.on(/description/i).respond('bla bla\n')
			.on(/keywords/i).respond('\n')
			.on(/category/i).respond('\n')
			.on(/brands/).respond('\n')
			.on(/JavaScript/).respond('\n')
			.on(/Sass/).respond('n\n')
			.on(/status/).respond('\n')
			.on(/team email/).respond('\n')
			.on(/slack channel/).respond('\n')
			.on(/Github team/).respond('\n')
			.on(/right/).respond('\n')
			.exist('./bob/')
			.exist('./bob/src/js')
			.exist('./bob/test/js')
			.exist('./bob/demos')
			.exist('./bob/.github')
			.notExist('./bob/src/scss')
			.notExist('./bob/test/scss')
			.notExist('./bob/demo/demo.scss')
			.exec('rm -rf bob')
			.end(done)
	});
});
