name: npm audit fix

on:
 schedule:
   - cron: 0 0 * * * # Runs at 00:00 UTC every day

# on:
#   push:
#     branches:
#       - 'master'

jobs:
  npm-audit-fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ybiquitous/npm-audit-fix-action@v2.1.1
        with:
          github_token: ${{ secrets.ORIGAMI_GITHUB_TOKEN }}
